### ISSUE TITLE
RangeError: Maximum call stack size exceeded when serializing complex recursive union schemas.

### ISSUE THREAD

**Issue by TomiS** [DZakh/rescript-schema#74]
Hey, I ran into this rather interesting bug which originates to `validateJsonableSchema` function, I believe. I think it relates to wrapping a recursive (union?) schema inside a non-recursive schema. Or at least that's how I can cause the bug reliably.

I made a somewhat minimal repro. It can be found in [this repository](https://github.com/TomiS/schema-test). See readme.md

**Comment by DZakh** [comment]
Thanks. The `validateJsonableSchema` just doesn't support recursive schemas. I planned to rewrite it for a long time because of this and another reason, but since there were no recursive users, I postponed it :) 

Looks like I have a reason to do so now 😅

For now, you can use `serializeToUnknownWith`, which doesn't have the `validateJsonableSchema` check.

**Comment by TomiS** [comment]
Very nice. Thanks for addressing this so quickly. I'm on vacation right now but will try out version 8 when it's released - or use the workaround meanwhile.

**Comment by DZakh** [comment]
Letting you know, that I found a bug with infinit loop when recursive schema fails parsing. I'll release 7.0.2 with a fix asap.

**Comment by DZakh** [comment]
`7.0.2` is published. I recommend you updating

**Comment by DZakh** [comment]
I release https://github.com/DZakh/rescript-schema/releases/tag/v8.0.0 with a fix 🚀
