### ISSUE TITLE
.recursive is missing from TS api

### ISSUE THREAD

**Issue by dearlordylord** [DZakh/rescript-schema#80]
with `"rescript-schema": "^8.0.1",`,

and `import * as S from "rescript-schema";`,

`S.recursive` doesn't seem to be there

I can use all other methods though, except .recursive

**Comment by DZakh** [comment]
Thank you for letting me know. I've added in the `8.0.2` patch release https://github.com/DZakh/rescript-schema/releases/tag/v8.0.2

The JS/TS mode just recently started getting more popularity so that some parts might be unpolished. I'm interested to listen to more feedback about using rescript-schema in TypeScript 🙏
